apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBywLs5ejfmRGduXvMCNgIRqSMkg20ZeK8B2zBckKYkRrcuAhyNfMrmgbNqk7v+lyFpzGU/IyYZFZJs8SgHDfN+4aXM41y3YmNfGpsxXL3kWObgU/F6WtKRaeXPYqT0k8Rvw6VIB2FkVizUabs8NbiyKENIQLixX2eGukS1WJvPKYBgnn1mnDNhRmrLRcGghEMuoWQQ4DtOAMLSqY7Wphd285QYD/Apgg3OZbqw3TZxW2kUsXm8EnfVTjU0LkcXOwfaMZ1Cuz+YXuvtpLo7AtoHO7/yQjIQ4uzmmc5L0Q0bIxBHligBiFrHucT4ViNf/ONluygBicwvDuY/0nGJ7q5SCg4hR02Lo+thM8RyH/qsgU8Ch4WQ0IgcI7FxCasl+ooJhaHhuwVM8k8axkq6YgtpdTxcB0ENC7mu4grO8K9spjuu0osuAE00tWKwLYpp4Zj+Yv1JLVnw/ZDbkAZrv6McOzVBGgmeeWTosZFbii1I0gCrym4PbO6zQH2k9wsgg9mg0OHsZFlDibi51HT3hpjNzn5SMgNORQSycTbVKAlQ8GZMSeZGcRLLrmbZUo0LZzRklFzIKvf/Vrym97EX3BWoJrfASKdIa4X/emMLiY/J4c/rHPBckPufnF8hTJhnEDoyhvdtCVB/R+thv3mp/fA+IcDbilJziWeEx4AF2wrHSgRyjcV7jUQz+DJh0f0CaNFA7+Ut8REDvQL4CIgG80MoKHIzN2VNPYkymEA+p6+8dzUiGfaoqMwR
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

