apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAs6UEyZYjFPVpNaYDOiUtBk2mzd6ayFHyjTHEFLu0etB1Rs6DTEfnUytlNK/LPgVri5gLefYsX49M1ofzOde6HlxrEB+WQz32qgxewxkZoz/U3tkZKK9p16utCQlhdPWKaRBwN+OM9ryAVlcdMNJnI0u+5H6C5MbaCW/p64KCS3Wk4H2VQkRucbtyd+0yps5YOzjV4tM/r4u05wxhvi3xXu0u/mYLmA6f4wKAyDEgxtZ4OmwLtSOor3PMVkhv3f9UuEI3sGxXoqyC/R4swbfFn7y3yIoU/aXKFoP4z0+a4CqSpESisuzewUMsTgYZe/lFHDjnQkDQcKkvNVlryAHNJY22EpeTSJGYlZtK9iKsCvjVP0t8lESS+hyiffHCJeG3h/0lx8+vsk3WQFd39eWvJsYYxWt7AWzwB3fUVAqv+ifGhzGEPXVPEabgK82cx0WfYiRFfMePGkufQgh4ZK+MbiyXWF5HRHFdHlDJlSHY1C9Adav105V7Xj5HC3mXRc4LlqThBTe2OuUTDUhv9MZW8R+7FyJDDm9J4DoNRXTmwQKQdlybOQtm11ukwfTAvC/fVnMQlDFdFNR4UnU0saeqWvnrDua4UYdVACcjeo38/xCMam5BVeTjmrcLJTfgY253iHgKKQDFuXdQavURmtw9pO9GkM9v01iunAlS/jshPoj+Aa6INmiVhJkuQz1DYPFhdSj87ETYZVkHuSIv5mMj8pXxLvkI+EE6XR6alZzFbQ1sAzZNCf3At
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

