apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBcFzXvRCUEtkaD3/qQp6GF09fMR03QB43sQiw+SAy9JVJdRLg17Ai6haGxxwPnQ9+jv65n5uvlr/5WYLpNz01iKFYRUlnA+6sad0Ht/tHmjsOs5eg5N923jOpZFtsA3HnoH3x0sRqEu2hvjgou9uEXIukBHgcsJ+H+0bIdC3E35TP0K58e5pIsehO5xs9uJz0NJekv9+vNGmHBLJMEMQEGb6NoT52XRoDYrKOdC22mFR7h+ftD2FJC9Ztm6Jx56S4JoxRcA/ftYxiY5bu2AL78YOXnfcUBQSdRr71OqYuX2fzeQGz/98YuPAdToXMPD4mhSJwcwjwQvDVJZMSKW2zbCzisj3dWP8Zg6ruGbuc2d1iX/NxTAiNEEUIkjiXPHxaop5tNPl1CRmiUxLOQMo9Qcf+BpJNW0CFe6Mz0LvYVg+kvnFP7KH83cwERLh3B6j9+T3Tk+t8uWrhNMt3vuAc3Q8iOK9WYal/4RGTlI5D/AaTVhSZ0Y1WxHMBxYPD0pTW0aZ80rGW08Mv7ZqfTGEeJ5PEGu9pQOkzfw5/IOVT84zquvby0wUtbAhQEQO+bS8NQuBF+StULeuItXdm8fzjJfjY6hNZlydH/HMZuBM4bfICdFK9h7e0uvsdi1Fxfpel2qb8BXeqMR99MXZONBHHYyxZjzPFF4nnyf4zRT+Z32BhhnVNXn0fbVa94UwDnx9m2xvT7ebeF1ECz6e9WG/zH29UEtdaWZtaOzDnp+g1ljKr6HFK72yMq
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

