apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBwH/XNodBL1lR/P06Ycg+r/hB4txEIuG4j+TFtTawsf9z7xhKZWi4KudXknbItxoMBtgySZ21QEr57h6AUaGHpD41s2HAYRLhFGOckG7w7bSCA8NF1MuALZ5mSG2s8RBjBWgoFVtZb/0lWIFAiIX9VksQnVDJT4cIoh0l5j/ezkvS0mIMtxnqfK/BerU8wzXEe47SH1HhPvb5jPv18iG6ZMheKYXe7F+64crWVEH6kst/bfYR5NuZAlO49afnj/2KQvdpbIz+QC9zEiWLyStJooyFEhMjump5B7DK3GJcu8liUCFq+KLlq1JMMvi3A0BS2kRJmuy0Q9OqLWGQJqZy5vq281W24tYOjjkPN2cfo597K9WM5J9Y9/cM4vCA5Dvnd7RbpFgWH5USZaqcJo9p03bt7Yvr2MDK82q7VFcGSDWAo/biXLmoYOzCgf4Fu90fqz+a8iUbrjNmlcwBe618zhsO7CcSbDMyfbV7KSv5BJ7Ns12ns1+P66TG1jFrSb9wX1MdNVJs3N36LfLXHOQsvlH/OZS9iwsEmXxmc2dTIf3h+osNdtZaSuLrxQ1WWUkA9BohEEzyGF+USL7kY75WcTHSuyN55Rq6FgmrOf9MoA41fmiHHq8aaFFbs/7O2ldQxthFEPwInxe//81zMyXkkkmNT8kWLYS7DlsHJ6aop+yhQ9hX0uEFrmzGQ9Scb5Ty+VfRsfbQFbxFUh41gHjIxIzxaTQd5usPVHHKdaEOOG5aUI0bYtDhV
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

