apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBNSg2i8nOlIAGE2yMUP6fVUhNdxn/BBwG2zF/sY2scxYu8y3F98YAwdRM9ZIwqnEU+HoZj0OdAS4/+vSyzwr82LqYUM6RChgsAHUvaPIZeIoiMVas7cB4gjMQ+FaIw2XpXLWOhFKPl4l/tP7OZBjq4yb3kx5Z4ST1R51Pnxlg1eYBdFSou+9j14o2rD5JUjNHE9utpIZPHV/eo1HdD5WXZdMDoABMLcoy0xrTA+Hyfdib3AN48h4gPnRZ4+yrMDyHQEdQ/A/0s2tbsv2Y/P9CfFpzTAu/K7vRtQhZ/r3B7UoVmdFQrf8BY+B5TFyQpvxJ7i8pzvTJjeJocSRGhP2DSNOfd1KrPOK1hnlUEYtCDPGRa86Hx7jbRod2G7jzeIEna1mWc+2lwSGiPq5+Wz2cpmlKqXhAAxLZ+XxyYo9pvMVhSOYPrRMuhnfDI8QSc6s0CHGAZaCfBfn2h+Yqd1+cqdVCOIR2AHN2oPp4x7bD2dr7lpaW7nop4Ahw5ZNvd1zvI1D5x2L3/yceQfDNzVVZHOHitoPk7X5T9A2gq8WoJvJ3h9ck52E2RsMIhCu3rEXGQ6ZqL4+qOZ5c86+7wwIE2yXJs911uj9kbDkOynQvdW22Wthngt4dfExm1VlniguJL81nCttCTwm/XlcHyROVN1fLMCVvGp0XKVYhpUn/K0/CE+y12IgqnSWzzVRKUrNIuBC96QA1k7q2qzGzBEdcNmlQWrzRCHtdCz4GDWJ3RXrObYYG+UXIO
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

